function blfr_builder

    mex blfr.c...
        zlib/adler32.c...
        zlib/crc32.c...
        zlib/inffast.c...
        zlib/inflate.c...
        zlib/inftrees.c...
        zlib/zutil.c...
        -Izlib...
        -outdir ..

end
