function blfw_builder

    mex blfw.c...
        zlib/adler32.c...
        zlib/crc32.c...
        zlib/inffast.c...
        zlib/inflate.c...
        zlib/deflate.c...
        zlib/inftrees.c...
        zlib/zutil.c...
        zlib/trees.c...
        -Izlib...
        -outdir ..

end
